### ISSUE TITLE
Error while installing second  Solr instance on the same machine

### ISSUE THREAD

**Issue by whuu** [SoftServeInc/SitecoreInstallExtensions#55]
When I install second instance on same machine Solr is not installed. 
Parameters:

$prefix = "ci-unicorn"
$sitecoreSiteName = "$prefix.local" 

$XConnectCollectionService = "$prefix.xconnect"

$SolrHost = "solr-unicorn.local"
$SolrUrl = "https://solr-unicorn.local:8984/solr" 
$SolrRoot = "C:\solr-unicorn.local\solr-6.6.2"
$SolrService = "PSSolrServiceUnicorn"

Rest of parameters are default. There is already instance installed, which uses solr on 8983 and default paths.

It looks that parameters are not used during solr installation.
This leads to exception:

[------------------------------------------------------------------------------------------------------------------- CleanCores : EnsurePath -------------------------------------------------------------------------------------------------------------------]
VERBOSE: Resolving ConfigFunction extension 'joinpath'
VERBOSE: Resolved 'Invoke-JoinPathConfigFunction'
VERBOSE: Resolving ConfigFunction extension 'joinpath'
VERBOSE: Resolved 'Invoke-JoinPathConfigFunction'
VERBOSE: Resolving ConfigFunction extension 'resolvepath'
VERBOSE: Resolved 'Invoke-ResolvePathConfigFunction'
VERBOSE: Invoke-ResolvePathConfigFunction
VERBOSE: Resolving path: C:\solr-unicorn.local\solr-6.6.2
Install-SitecoreConfiguration : Unable to parse [variable('Core.Root')] - Exception calling "Evaluate" with "2" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to 
parse [joinpath(variable('Solr.Server'), variable('Xdb.Name'))] - Exception calling "Evaluate" with "2" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to parse 
[joinpath(variable('Solr.FullRoot'), 'server', 'solr')] - Exception calling "Evaluate" with "2" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to parse 
[resolvepath(parameter('SolrRoot'))] - Exception calling "InvokeWithContext" with "2" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 
'C:\solr-unicorn.local\solr-6.6.2' because it does not exist.""""
At line:103 char:2

**Comment by rsenk** [comment]
A new release of SIX (1.0.0.10), improves Solr installation process.  It's possible to have multiple Solr instances.
