### ISSUE TITLE
http hardcoded in Invoke-InstallPackageTask.ps1

### ISSUE THREAD

**Issue by mklim-softserve** [SoftServeInc/SitecoreInstallExtensions#94]
Hello,
I have my site on https and while Invoke-InstallPackageTask.ps1 I got an issue
"The request failed with HTTP status 404: Not Found."
[files.181121 (10).log](https://github.com/SoftServeInc/SitecoreInstallExtensions/files/2607125/files.181121.10.log)

kind regards
Gosia

**Comment by rsenk** [comment]
Solved in version 1.2.0.2
